spring.application.name=control-plane
spring.datasource.url=jdbc:postgresql://localhost:5432/research
spring.datasource.username=research
spring.datasource.password=research
spring.jpa.hibernate.ddl-auto=validate

