apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: retrieval-service-cicd
  labels:
    app.kubernetes.io/name: retrieval-service-cicd
    app.kubernetes.io/part-of: retrieval-service-cicd-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: retrieval-service-cicd
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80