name: agent-service

on:
  push:
    branches: [main]
    paths:
      - agent-service/**
      - common/**
      - pom.xml
      - .github/workflows/agent-service.yml
      - .github/workflows/_build-deploy.yml
  workflow_dispatch:

concurrency: ${{ github.workflow }}

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_build-deploy.yml
    secrets: inherit
    with:
      image: agent-service
      dockerfile: ./agent-service/Dockerfile
      manifests: ./agent-service/k8s
