name: control-plane

on:
  push:
    branches: [main]
    paths:
      - control-plane/**
      - common/**
      - pom.xml
      - .github/workflows/control-plane.yml
      - .github/workflows/_build-deploy.yml
  workflow_dispatch:

concurrency: ${{ github.workflow }}

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_build-deploy.yml
    secrets: inherit
    with:
      image: control-plane
      dockerfile: ./control-plane/Dockerfile
      manifests: ./control-plane/k8s
