name: extractor

on:
  push:
    branches: [main]
    paths:
      - extractor/**
      - .github/workflows/extractor.yml
      - .github/workflows/_build-deploy.yml
  workflow_dispatch:

concurrency: ${{ github.workflow }}

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_build-deploy.yml
    secrets: inherit
    with:
      image: extractor
      dockerfile: ./extractor/Dockerfile
      context: ./extractor
      manifests: ./extractor/k8s
